name: Deploy

on:
  push:
      branches: [main]

jobs:
  deploy:
      name: Deploy to Datalake
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2

        - name: Set up Python 3.9
          uses: action/setup-python@v2
          with:
            python-version: 3.9

        - name: Hashicorp - Setup Terraform 
          uses: hashicorp/setup-terraform@v1.1.7
        
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ""
            aws-secret-access