name: test on PR

on:
  pull_request:
      branches: [main]

jobs:
  test:
      name: Test infra on PR
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2

        - name: Set up Python 3.9
          uses: action/setup-python@v2
          with:
            python-version: 3.9

        - name: Hashicorp - Setup Terraform 
          uses: hashicorp/setup-terraform@v1.1.7
        
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secret.AWS_SECRET_KEY_ID }}
            aws-secret-access-key: ""
            aws-region: us-east-2

        - name: Iac Apply
          env:
            COMMAND_IAC: terraform
          run: |
            cd infraestructure
            $COMMAND_IAC init
            $COMMAND_IAC validate
            $COMMAND_IAC plan
            